// <auto-generated />
namespace LearnHub.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nonCoreTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nonCoreTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202008191023298_nonCoreTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
